FROM python:3.11-slim
WORKDIR /app
COPY services/kafka_rabbitmq_relay/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY services/common /app/common
COPY services/kafka_rabbitmq_relay/main.py /app/main.py
CMD ["python", "main.py"]
