apiVersion: v1
kind: ConfigMap
metadata:
  name: product-platform-config
  namespace: apps
data:
  KAFKA_BOOTSTRAP_SERVERS: kafka.confluent.svc.cluster.local:9092
  ELASTICSEARCH_URL: http://single-es-coord.elasticsearch.svc.cluster.local:9200
  REDIS_URL: redis://redis.messaging.svc.cluster.local:6379/0
  RABBITMQ_HOST: rabbitmq.messaging.svc.cluster.local
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: guest
  RABBITMQ_PASSWORD: guest
  PRODUCTS_INDEX: products
  REVIEWS_INDEX: product_reviews
  TOPIC_PRODUCT_REVIEWS: product-reviews
  TOPIC_PRODUCT_REVIEW_BATCHES: product-review-batches
  TOPIC_PRODUCT_REVIEW_DLQ: product-review-dlq
  TOPIC_PRODUCT_REVIEW_BATCHES_DLQ: product-review-batches-dlq
  QUEUE_REVIEW_SUMMARIZATION: review_summarization_jobs
  PRODUCT_COUNT: "500"
  PRODUCE_INTERVAL_SECONDS: "1"
  WINDOW_SECONDS: "60"
  MAX_BATCH_SIZE: "20"
  USE_FAKE_LLM: "true"
