apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: product-platform
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: product-ui.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - host: product-api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: product-api
                port:
                  number: 80
