apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: product-reviews-es-sink
  namespace: confluent
spec:
  class: "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector"
  taskMax: 2
  connectClusterRef:
    name: kafka-connect
  configs:
    topics: "product-reviews"
    connection.url: "http://single-es-coord.elasticsearch.svc.cluster.local:9200"

    transforms: "CreateKey,ExtractKey"
    transforms.CreateKey.type: "org.apache.kafka.connect.transforms.ValueToKey"
    transforms.CreateKey.fields: "review_id"
    transforms.ExtractKey.type: "org.apache.kafka.connect.transforms.ExtractField$Key"
    transforms.ExtractKey.field: "review_id"

    key.ignore: "false"
    schema.ignore: "true"
    write.method: "UPSERT"
    behavior.on.null.values: "IGNORE"
    topic.index.map: "product-reviews:product_reviews"

    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter.schemas.enable: "false"
